# Site settings
title: Uzziel Perez
description: Uzziel Perez GitHub Page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://uzzielperez.github.io
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br


# User settings
username: Uzziel Perez
user_description: Novice Particle Hunter. Open Science Lover. Football Nerd.
user_title: HEP PhD student
email: cperez3@crimson.ua.edu
twitter_username: Uzziesh
github_username:  uzzielperez
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      future: true
